#!/usr/bin/env python
"""Compute the per-track results shown on the results site (docs/index.html).

Runs the real MERT / beat-tracking / SSM / Fusion pipeline over every bundled
example clip and injects the output (self-similarity matrices, structure
estimates, gates) into docs/index.html between the `site-data` markers. The data
is embedded rather than fetched, so the page stays a single self-contained file
that hosts on GitHub Pages with no server.

Re-run this whenever the demo model or the example set changes:

    python scripts/build_site_data.py

Requires the demo extra:  pip install -e ".[demo]"
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BEGIN = "  /* BEGIN:site-data"
END = "  /* END:site-data */"


def _clean_title(title: str) -> str:
    """Drop the part number and the em dash the asset titles use.

    "Brahms — Hungarian Dance No. 5 · pt1" -> "Brahms, Hungarian Dance No. 5".
    The site copy avoids em dashes, and these labels are rendered straight onto it.
    """
    title = title.split(" · pt")[0]
    return title.replace(" — ", ", ").strip()


def collect(assets: Path, device: str) -> list[dict]:
    from falsetto.demo.studio import load_analyzer
    from falsetto.utils.audio_io import load_audio

    analyzer, meta = load_analyzer(assets, device)
    examples_dir = assets / "examples"

    tracks: list[dict] = []
    for entry in meta.get("examples", []):
        path = examples_dir / entry["file"]
        if not path.exists():
            print(f"  skip (missing): {entry['file']}", file=sys.stderr)
            continue
        waveform, sr = load_audio(str(path), mono=True)
        result = analyzer.analyze(waveform, sr)
        n = max(result.features.n_segments, 1)
        # features.ssm is padded to SEQ_LEN; crop to the real segment count.
        ssm = result.features.ssm[:n, :n].tolist()
        tracks.append(
            {
                "key": path.stem,
                "label": _clean_title(entry["title"]),
                "expect": entry["expected"],
                "source": entry.get("source", ""),
                "n": n,
                "coherence": round(float(result.coherence), 4),
                "band": result.band,
                "mean_gate": round(float(result.mean_gate), 4),
                "duration": round(float(result.features.duration_sec), 1),
                "downbeats": len(result.features.downbeats),
                "ssm": [[round(float(v), 4) for v in row] for row in ssm],
            }
        )
        t = tracks[-1]
        print(f"  {t['label']:<44} {t['coherence']*100:5.1f}%  {t['band']}")
    return tracks


def render_block(tracks: list[dict]) -> str:
    """The generated JS block: the full track set, plus the worked-example pair."""
    # The worked example contrasts a real recording against pure noise; pick both
    # out of the same run so the page never disagrees with itself.
    def index_where(pred, default=0):
        return next((i for i, t in enumerate(tracks) if pred(t)), default)

    i_struct = index_where(lambda t: t["source"] == "real" and t["expect"] == "structured")
    i_unstruct = index_where(lambda t: t["source"] == "noise", len(tracks) - 1)

    lines = [
        BEGIN + ": generated by scripts/build_site_data.py; do not edit by hand */",
        "  var TRACKS = " + json.dumps(tracks, ensure_ascii=False, separators=(", ", ": ")) + ";",
        f"  var SSM = {{ structured: TRACKS[{i_struct}], unstructured: TRACKS[{i_unstruct}] }};",
        END,
    ]
    return "\n".join(lines)


def inject(page: Path, block: str) -> None:
    text = page.read_text(encoding="utf-8")
    lines = text.split("\n")
    starts = [i for i, ln in enumerate(lines) if ln.startswith(BEGIN)]
    ends = [i for i, ln in enumerate(lines) if ln.startswith(END)]
    if not starts or not ends:
        raise SystemExit(
            f"{page}: could not find the site-data markers. Expected a line starting with\n"
            f"  {BEGIN!r}\nand one starting with\n  {END!r}"
        )
    lo, hi = starts[0], ends[0]
    if hi < lo:
        raise SystemExit(f"{page}: site-data markers are out of order")
    page.write_text("\n".join(lines[:lo] + block.split("\n") + lines[hi + 1:]), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--assets", default=str(ROOT / "demo_assets"), help="demo assets dir")
    p.add_argument("--device", default="auto")
    p.add_argument("--page", default=str(ROOT / "docs" / "index.html"))
    args = p.parse_args(argv)

    print("analyzing example tracks (real pipeline)...")
    tracks = collect(Path(args.assets), args.device)
    if not tracks:
        print("no example tracks found; nothing to write", file=sys.stderr)
        return 1
    inject(Path(args.page), render_block(tracks))
    print(f"\nwrote {len(tracks)} tracks into {args.page}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
